version: '3.1'
services:

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: XM809HN24KA06
      POSTGRES_DATABASE: app
      POSTGRES_USER: app
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - '5432:5432'